on: [workflow_dispatch]

env: 
  subscription: ${{ secrets.AZURE_SUBSCRIPTION }}
  rg_name: <rg-name>
  service_name: <service-name>
  app_name: <app-name>
  location: <region>

jobs:
  Create_service_and_app_job:
    runs-on: ubuntu-latest
    name: Create service instance and app
    steps:
      - name: Checkout Github Action
        uses: actions/checkout@master

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SUBSCRIPTION_SP }}

      - name: Create service instance and app
        run: bash ${{ github.workspace }}/.github/workflows/create_service_app.sh
        shell: bash
        env: 
          subscription: ${{ secrets.AZURE_SUBSCRIPTION }}
          rg_name: ${{ env.rg_name }}
          service_name: ${{ env.service_name }}
          app_name: ${{ env.app_name }}
          location: ${{ env.location }}