on: [workflow_dispatch]

env: 
  subscription: ${{ secrets.AZURE_SUBSCRIPTION }}
  rg_name: ruoyu-test-rg
  service_name: ruoyu-test
  app_name: hello
  location: eastasia

jobs:
  Create_service_and_app_job:
    runs-on: ubuntu-latest
    name: Create service instance and app
    steps:
      - name: Checkout Github Action
        uses: actions/checkout@master

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SUBSCRIPTION_SP }}

      - name: Create service instance and app
        run: bash ${{ github.workspace }}/.github/workflows/create_service_app.sh
        shell: bash
        env: 
          subscription: ${{ secrets.AZURE_SUBSCRIPTION }}
          rg_name: ruoyu-test-rg
          service_name: ruoyu-test
          app_name: hello